## GET ALL

http://localhost:8080/estudiantes

## GET ID

http://localhost:8080/estudiantes/4

## CREATE

POST http://localhost:8080/estudiantes HTTP/1.1
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Rendon",
    "edad": 23
}

## UPDATE

PUT http://localhost:8080/estudiantes/4 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Joe",
    "apellido": "Hurtado",
    "edad": 30
}

## DELETE

DELETE  http://localhost:8080/estudiantes/4 HTTP/1.1
